name: Get UTC DateTime

on:
  workflow_call:
    outputs:
      UTC-DateTime:
        description: "The DateTime as UTC formatted as yyyyMMddHHmmss."
        value: ${{ jobs.Get-UTC-DateTime.outputs.UTC-DateTime }}

jobs:
  Get-UTC-DateTime:
    name: Get UTC DateTime
    runs-on: windows-latest

    outputs:
      UTC-DateTime: ${{ steps.Get-UTC-DateTime.outputs.UTC-DateTime }}

    steps:
      - name: Get current DateTime
        id: Get-UTC-DateTime
        run: echo ('UTC-DateTime=' + [System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss")) >> $env:GITHUB_OUTPUT
