name: Get UTC DateTime

on:
  workflow_call:

    outputs:
      utc-datetime:
        description: "The DateTime as UTC formatted as yyyyMMddHHmmss."
        value: ${{ jobs.utc-datetime.outputs.utc-datetime-output }}

jobs:
  utc-datetime:
    name: Get UTC DateTime
    runs-on: windows-latest

    outputs:
      utc-datetime-output: ${{ steps.get-datetime.outputs.UTCDateTime }}

    steps:
    - name: Get current UTC DateTime
      id: get-datetime
      run: echo ('UTCDateTime=' + [System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss")) >> $env:GITHUB_OUTPUT